services:
  opa:
    image: openpolicyagent/opa:0.66.0
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies:ro
